In [2]:
import numpy as np
# basic array creation

In [ ]:
arr = np.array([1,2,3,4])
arr 

array([1, 2, 3, 4])

In [4]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [5]:
np.array(a)

array([1, 2, 3, 4])

In [5]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Array generation functions
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
# Print zeros array zeros(row, column)
arr = np.zeros(6)
arr
arr1 = np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Print ones array ones(row, column)
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# Print linspace array linspace(start, end, number of elements)
arr = np.linspace(0,10,5)
arr
# Print identity matrix identity(size)
arr = np.eye(5)
arr
# Print random array random(size) - it will generate random numbers between 0 and 1
arr = np.random.rand(4,4)
arr
# It will generate random integers between a given range randint(start, end)
arr = np.random.randint(1,100,10)
arr
# Print random integers in a given range randint(start, end, size) it will generate random integers in a given range with specified size
arr = np.random.randint(1,100,(3,4))
arr
# --- IGNORE ---


array([[47, 48, 20, 60],
       [74, 42, 74, 70],
       [81, 29, 44, 66]], dtype=int32)

In [17]:
# Array Attribute Information
arr = np.random.randint(1,100,(3,4))
arr


array([[ 3,  9, 69, 74],
       [20,  2, 36, 89],
       [78, 34, 37, 78]], dtype=int32)

In [ ]:
# Array Methods
arr.shape # it will give the shape of the array
arr.ndim # it will give the number of dimensions
arr.size # it will give the total number of elements in the array
arr.dtype # it will give the data type of the array
arr.itemsize # it will give the size of each element in bytes
arr.nbytes # it will give the total size of the array in bytes
arr.astype('float32') # it will convert the array to the specified data type
arr.max() # it will give the maximum value in the array
arr.min() # it will give the minimum value in the array
arr.sum() # it will give the sum of all elements in the array
arr.mean() # it will give the mean of all elements in the array
arr.std() # it will give the standard deviation of all elements in the array
arr.var() # it will give the variance of all elements in the array
arr.argmax() # it will give the index of the maximum value in the array
arr.argmin() # it will give the index of the minimum value in the array
arr.reshape(4,3) # it will reshape the array to the specified shape 

array([[ 3,  9, 69],
       [74, 20,  2],
       [36, 89, 78],
       [34, 37, 78]], dtype=int32)

In [47]:
# Array indexing and slicing

array = np.arange(11,21)
array
array[3:8] # slicing from index 3 to 7
array[3::2] # slicing from index 3 to end with step 2
array[:5] # slicing from start to index 4
array[-5:] # slicing last 5 elements
array[::-1] # reversing the array


# Array Indexing and Slicing in 2D array or Matrix
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr
arr[0,0] # it will give the element at the specified index
arr[1,2] # it will give the element at the specified index
arr[:,2] # it will give all rows of the specified column
arr[1,:] # it will give all columns of the specified row
arr[0:2,1:4] # it will give the specified rows and columns
arr[::2,::2] # it will give every second row and every second column
arr[::-1,::-1] # it will reverse the array
arr.flatten() # it will flatten the array to 1D
arr.T # it will transpose the array
arr.reshape(5,3) # it will reshape the array to the specified shape
arr.reshape(-1) # it will flatten the array to 1D
arr.reshape(15,1) # it will reshape the array to the specified shape
arr.reshape(1,15) # it will reshape the array to the specified shape
#  --- IGNORE ---


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# Array from tuple
t = (1,2,3,4,5)
np.array(t)
# array tuple methods and indexing
t.index(3) # it will give the index of the specified element
t.count(2) # it will give the count of the specified element

# array from set
s = {1,2,3,4,5}
np.array(s)
# array from dictionary
d = {'a':1,'b':2,'c':3}
np.array(d)
# array from string
str1 = "Hello World"
np.array(list(str1))
np.array(str1)
# array from bytes
b = b'Hello World'
np.array(list(b))
np.array(b)


array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [4]:
# Array boolean indexing
arr = np.array([10,15,20,25,30,35,40,45,50])
arr > 25
arr[arr > 25]
bool_index = arr %2 == 0
bool_index

arr = arr[bool_index]
arr

array([10, 20, 30, 40, 50])

In [ ]:
# Array Operations in NumPy
# Rules of Array Operations:
# 1. Both arrays must have the same shape.
# 2. Operations are performed element-wise.
# 
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
# Addition 
a1 + a2
# subtraction
a2 - a1
# multiplication
a1 * a2
# division
a2 / a1
# exponentiation
a1 ** 2
# modulus
a2 % a1 
# Broadcasting in NumPy
# When the shapes of the arrays are not the same, NumPy will try to broadcast the
l = [1,2,3,4,5]
arr = np.array(l)
arr + 10
# Broadcasting with 2D array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d + 5
# Broadcasting with different shapes
arr1d = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d + arr1d
# Broadcasting with 1D and 2D array
arr1d = np.array([1,2,3])   
arr2d = np.array([[1],[2],[3]])
arr2d + arr1d

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
# Deep and shallow copy in NumPy
# Deep copy : it creates a new array with its own data
arr1 = np.array([1,2,3,4,5])
# Shallow copy : it creates a new array that references the same data as the original array
arr2 = arr1
arr2[0] = 10
arr1    # it will reflect the change made in arr2
# example of deep copy
arr3 = arr1.copy()
arr3[1] = 20
arr3
arr1    # it will not reflect the change made in arr3

array([10,  2,  3,  4,  5])

In [ ]:
# Matrix Operations in NumPy
# Matrix Addition
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
m1 + m2
# Matrix Subtraction
m2 - m1
# Matrix Multiplication
m1 * m2
m1.dot(m2)
# Matrix Transpose
m1.T
# Matrix Determinant
np.linalg.det(m1)
# 
m1 @ m2
# matrix product
np.matmul(m1,m2)
# --- IGNORE ---

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [37]:
# Adavnced Array Creation 
# Stacking arrays
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
# Vertical stacking
np.vstack((a1,a2))
# Horizontal stacking
np.hstack((a1,a2))
# column stacking
np.column_stack((a1,a2))
# row stacking
np.row_stack((a1,a2))
# Depth stacking
np.dstack((a1,a2))


# Splitting arrays
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# Split into 2 arrays   
np.split(arr,2)
# Split into 3 arrays
# np.split(arr,3)
np.array_split(arr,3)
# vertical split
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.vsplit(arr2d,3)
# horizontal split
np.hsplit(arr2d,2)
# depth split
np.dsplit(arr2d.reshape(3,2,2),2)
for i in arr2d:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


C:\Users\HP\AppData\Local\Temp\ipykernel_12424\3830121037.py:12: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a1,a2))
