In [3]:
a = 23
b = 20
a + b

43

In [4]:
import numpy as np

In [6]:
# Valid sudoku board
board = [
  ["5","3",".",".","7",".",".",".","."],    
  ["6",".",".","1","9","5",".",".","."],
  [".","9","8",".",".",".",".","6","."],
  ["8",".",".",".","6",".",".",".","3"],
  ["4",".",".","8",".","3",".",".","1"],
  ["7",".",".",".","2",".",".",".","6"],
  [".","6",".",".",".",".","2","8","."],
  [".",".",".","4","1","9",".",".","5"],
  [".",".",".",".","8",".",".","7","9"] 
]

np.array(board)

# Check sudoku is valid or not
def isValidSudoku(board):
    rows = {}
    cols = {}
    boxes = {}
    
    for r in range(9):
        for c in range(9):
            val = board[r][c]
            if val == '.':
                continue
            
            # Check row
            if (r, val) in rows:
                return False
            rows[(r, val)] = True
            
            # Check column
            if (c, val) in cols:
                return False
            cols[(c, val)] = True
            
            # Check box
            box_index = (r // 3, c // 3)
            if (box_index, val) in boxes:
                return False
            boxes[(box_index, val)] = True
            
    return True

# 
isValidSudoku(board)

# Create a proper sudoku board
sudoku_board = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    ])
# If the sum of each row, column and 3x3 sub-box is 45, then it's a valid sudoku
b = np.sum(sudoku_board, axis=1)
# b[b == 45]
for i in b:
    if i != 45:
        print("Invalid Sudoku")
        break
else:
    print("Valid Sudoku")

# slicing
sudoku_board[0:3, 0:3]
for i in range(0,9,3):
    for j in range(0,9,3):
        print(sudoku_board[i:i+3, j:j+3])   


Valid Sudoku
[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [7]:
# Get the shape of the matrix
sudoku_board.shape

(9, 9)

In [8]:
# find the average age of students in a class
ages = np.array([15, 16, 15, 14, 16, 15, 14, 15, 16, 14])
average_age = np.mean(ages) 
average_age

np.float64(15.0)

In [ ]:
# Exact math marks of all students
math_marks = np.array([88, 92, 79, 85, 90, 95, 80, 87, 91, 84])
# Calculate the standard deviation of math marks    
std_dev_math_marks = np.std(math_marks)
std_dev_math_marks


In [9]:
# Check if the sums of all rows, columns, and boxes are 45
row_sums = np.sum(sudoku_board, axis=1)
row_sums
col_sums = np.sum(sudoku_board, axis=0)
col_sums
box_sums = []
for i in range(0,9,3):
    for j in range(0,9,3):
        box = sudoku_board[i:i+3, j:j+3]
        box_sum = np.sum(box)
        box_sums.append(box_sum)    
box_sums
box_sums
all_sums = np.concatenate((row_sums, col_sums, box_sums))
all_sums
all_sums == 45
np.all(all_sums == 45)


np.True_

In [16]:
#  create a matrix of 5x3 of integer value like a student marks in different subjects
student_marks = np.array([[85, 90, 78],
                          [80, 85, 89],
                          [82, 88, 85],
                          [92, 91, 90],
                          [88, 87, 86]])    
student_marks
# let's calculate the average marks of each student
average_marks = np.mean(student_marks, axis=1)
average_marks

# column [english, math, science] average
# give the maths mark which is greater than 85
math_marks = student_marks[:, 1]    
math_marks[math_marks > 85]
# find the maximum marks in each subject
max_marks = np.max(student_marks, axis=0)
max_marks
# find the minimum marks in each subject
min_marks = np.min(student_marks, axis=0)
min_marks
# find the total marks obtained by each student
total_marks = np.sum(student_marks, axis=1)
total_marks
# let increase the marks of math by 5 for all students
student_marks[:, 1] += 5
student_marks
# find the median marks in science
median_science_marks = np.median(student_marks[:, 2])
median_science_marks
# find the variance of marks in english
variance_english_marks = np.var(student_marks[:, 0])
variance_english_marks
# find the indices of students who scored more than 90 in any subject
indices_above_90 = np.where(student_marks > 90)
indices_above_90
# get the shape of the student_marks matrix
student_marks.shape
# reshape the student_marks matrix to 3x5
reshaped_marks = student_marks.reshape(3, 5)
reshaped_marks
# transpose the student_marks matrix
transposed_marks = student_marks.T
transposed_marks
# flatten the student_marks matrix
flattened_marks = student_marks.flatten()
flattened_marks
# find unique marks obtained by students
unique_marks = np.unique(student_marks) 
# get me that student marks who scored exactly 85 in any subject
students_with_85 = np.where(student_marks == 85)
# get me that student who scored the highest total marks
total_marks = np.sum(student_marks, axis=1)
top_student_index = np.argmax(total_marks)
unique_marks
# student who score in two subjects more than 85
count_above_85 = np.sum(student_marks > 85, axis=1)
students_above_85_in_two_subjects = np.where(count_above_85 >= 2)
students_above_85_in_two_subjects
students_with_85
top_student_index

# If any student scored less than 80 in any subject, give them a retest
retest_indices = np.where(student_marks < 80)
retest_indices

(array([0]), array([2]))